// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2023, Linaro Ltd. All rights reserved.
 */

#include "qcom_pmic_tcpm_typec.h"
#include "qcom_pmic_tcpm_regs.h"

#define PM8150b_TYPEC_SNK_STATUS_REG				0x06
#define PM8150b_DETECTED_SNK_TYPE_MASK				GENMASK(6, 0)
#define PM8150b_SNK_DAM_MASK					GENMASK(6, 4)
#define PM8150b_SNK_DAM_500MA					BIT(6)
#define PM8150b_SNK_DAM_1500MA					BIT(5)
#define PM8150b_SNK_DAM_3000MA					BIT(4)
#define PM8150b_SNK_RP_STD					BIT(3)
#define PM8150b_SNK_RP_1P5					BIT(2)
#define PM8150b_SNK_RP_3P0					BIT(1)
#define PM8150b_SNK_RP_SHORT					BIT(0)

#define PM8150b_TYPEC_SRC_STATUS_REG				0x08
#define PM8150b_DETECTED_SRC_TYPE_MASK				GENMASK(4, 0)
#define PM8150b_SRC_HIGH_BATT					BIT(5)
#define PM8150b_SRC_DEBUG_ACCESS				BIT(4)
#define PM8150b_SRC_RD_OPEN					BIT(3)
#define PM8150b_SRC_RD_RA_VCONN					BIT(2)
#define PM8150b_SRC_RA_OPEN					BIT(1)
#define PM8150b_AUDIO_ACCESS_RA_RA				BIT(0)

#define PM8150b_TYPEC_STATE_MACHINE_STATUS_REG			0x09
#define PM8150b_TYPEC_ATTACH_DETACH_STATE			BIT(5)

#define PM8150b_TYPEC_SM_STATUS_REG				0x0A
#define PM8150b_TYPEC_SM_VBUS_VSAFE5V				BIT(5)
#define PM8150b_TYPEC_SM_VBUS_VSAFE0V				BIT(6)
#define PM8150b_TYPEC_SM_USBIN_LT_LV				BIT(7)

#define PM8150b_TYPEC_MISC_STATUS_REG				0x0B
#define PM8150b_TYPEC_WATER_DETECTION_STATUS			BIT(7)
#define PM8150b_SNK_SRC_MODE					BIT(6)
#define PM8150b_TYPEC_VBUS_DETECT				BIT(5)
#define PM8150b_TYPEC_VBUS_ERROR_STATUS				BIT(4)
#define PM8150b_TYPEC_DEBOUNCE_DONE				BIT(3)
#define PM8150b_CC_ORIENTATION					BIT(1)
#define PM8150b_CC_ATTACHED					BIT(0)

#define PM8150b_LEGACY_CABLE_STATUS_REG				0x0D
#define PM8150b_TYPEC_LEGACY_CABLE_STATUS			BIT(1)
#define PM8150b_TYPEC_NONCOMP_LEGACY_CABLE_STATUS		BIT(0)

#define PM8150b_TYPEC_U_USB_STATUS_REG				0x0F
#define PM8150b_U_USB_GROUND_NOVBUS				BIT(6)
#define PM8150b_U_USB_GROUND					BIT(4)
#define PM8150b_U_USB_FMB1					BIT(3)
#define PM8150b_U_USB_FLOAT1					BIT(2)
#define PM8150b_U_USB_FMB2					BIT(1)
#define PM8150b_U_USB_FLOAT2					BIT(0)

#define PM8150b_TYPEC_MODE_CFG_REG				0x44
#define PM8150b_TYPEC_TRY_MODE_MASK				GENMASK(4, 3)
#define PM8150b_EN_TRY_SNK					BIT(4)
#define PM8150b_EN_TRY_SRC					BIT(3)
#define PM8150b_TYPEC_POWER_ROLE_CMD_MASK			GENMASK(2, 1)
#define PM8150b_EN_SRC_ONLY					BIT(2)
#define PM8150b_EN_SNK_ONLY					BIT(1)
#define PM8150b_TYPEC_DISABLE_CMD				BIT(0)

#define PM8150b_TYPEC_VCONN_CONTROL_REG				0x46
#define PM8150b_VCONN_EN_ORIENTATION				BIT(2)
#define PM8150b_VCONN_EN_VALUE					BIT(1)
#define PM8150b_VCONN_EN_SRC					BIT(0)

#define PM8150b_TYPEC_CCOUT_CONTROL_REG				0x48
#define PM8150b_TYPEC_CCOUT_BUFFER_EN				BIT(2)
#define PM8150b_TYPEC_CCOUT_VALUE				BIT(1)
#define PM8150b_TYPEC_CCOUT_SRC					BIT(0)

#define PM8150b_DEBUG_ACCESS_SRC_CFG_REG			0x4C
#define PM8150b_EN_UNORIENTED_DEBUG_ACCESS_SRC			BIT(0)

#define PM8150b_TYPE_C_CRUDE_SENSOR_CFG_REG			0x4e
#define PM8150b_EN_SRC_CRUDE_SENSOR				BIT(1)
#define PM8150b_EN_SNK_CRUDE_SENSOR				BIT(0)

#define PM8150b_TYPEC_EXIT_STATE_CFG_REG			0x50
#define PM8150b_BYPASS_VSAFE0V_DURING_ROLE_SWAP			BIT(3)
#define PM8150b_SEL_SRC_UPPER_REF				BIT(2)
#define PM8150b_USE_TPD_FOR_EXITING_ATTACHSRC			BIT(1)
#define PM8150b_EXIT_SNK_BASED_ON_CC				BIT(0)

#define PM8150b_TYPEC_CURRSRC_CFG_REG				0x52
#define PM8150b_TYPEC_SRC_RP_SEL_MASK				GENMASK(1, 0)
#define PM8150b_TYPEC_SRC_RP_SEL_330UA				BIT(1)
#define PM8150b_TYPEC_SRC_RP_SEL_180UA				BIT(0)
#define PM8150b_TYPEC_SRC_RP_SEL_80UA				0

#define PM8150b_TYPEC_INTERRUPT_EN_CFG_1_REG			0x5E
#define PM8150b_TYPEC_LEGACY_CABLE_INT_EN			BIT(7)
#define PM8150b_TYPEC_NONCOMPLIANT_LEGACY_CABLE_INT_EN		BIT(6)
#define PM8150b_TYPEC_TRYSOURCE_DETECT_INT_EN			BIT(5)
#define PM8150b_TYPEC_TRYSINK_DETECT_INT_EN			BIT(4)
#define PM8150b_TYPEC_CCOUT_DETACH_INT_EN			BIT(3)
#define PM8150b_TYPEC_CCOUT_ATTACH_INT_EN			BIT(2)
#define PM8150b_TYPEC_VBUS_DEASSERT_INT_EN			BIT(1)
#define PM8150b_TYPEC_VBUS_ASSERT_INT_EN			BIT(0)

#define PM8150b_TYPEC_INTERRUPT_EN_CFG_2_REG			0x60
#define PM8150b_TYPEC_SRC_BATT_HPWR_INT_EN			BIT(6)
#define PM8150b_MICRO_USB_STATE_CHANGE_INT_EN			BIT(5)
#define PM8150b_TYPEC_STATE_MACHINE_CHANGE_INT_EN		BIT(4)
#define PM8150b_TYPEC_DEBUG_ACCESS_DETECT_INT_EN		BIT(3)
#define PM8150b_TYPEC_WATER_DETECTION_INT_EN			BIT(2)
#define PM8150b_TYPEC_VBUS_ERROR_INT_EN				BIT(1)
#define PM8150b_TYPEC_DEBOUNCE_DONE_INT_EN			BIT(0)

#define PM8150b_TYPEC_DEBOUNCE_OPTION_REG			0x62
#define PM8150b_REDUCE_TCCDEBOUNCE_TO_2MS			BIT(2)

#define PM8150b_TYPE_C_SBU_CFG_REG				0x6A
#define PM8150b_SEL_SBU1_ISRC_VAL				0x04
#define PM8150b_SEL_SBU2_ISRC_VAL				0x01

#define PM8150b_TYPEC_U_USB_CFG_REG				0x70
#define PM8150b_EN_MICRO_USB_FACTORY_MODE			BIT(1)
#define PM8150b_EN_MICRO_USB_MODE				BIT(0)

#define PM8150b_TYPEC_PMI632_U_USB_WATER_PROTECTION_CFG_REG	0x72

#define PM8150b_TYPEC_U_USB_WATER_PROTECTION_CFG_REG		0x73
#define PM8150b_EN_MICRO_USB_WATER_PROTECTION			BIT(4)
#define PM8150b_MICRO_USB_DETECTION_ON_TIME_CFG_MASK		GENMASK(3, 2)
#define PM8150b_MICRO_USB_DETECTION_PERIOD_CFG_MASK		GENMASK(1, 0)

#define PM8150b_TYPEC_PMI632_MICRO_USB_MODE_REG			0x73
#define PM8150b_MICRO_USB_MODE_ONLY				BIT(0)

/*
 * Undecided if macros should be used for the values,
 * or if it's best to just use the values directly
 */
static const u8 qptc_reg_snk_status_fields[] = {
	[SNK_RP_STD] = PM8150b_SNK_RP_STD,
	[SNK_RP_1P5] = PM8150b_SNK_RP_1P5,
	[SNK_RP_3P0] = PM8150b_SNK_RP_3P0,
	[SNK_TYPE_MASK] = PM8150b_DETECTED_SNK_TYPE_MASK,
};

QPTC_REG(SNK_STATUS, snk_status, PM8150b_TYPEC_SNK_STATUS_REG);

static const u8 qptc_reg_src_status_fields[] = {
	[SRC_RD_OPEN] = PM8150b_SRC_RD_OPEN,
	[SRC_RD_RA_VCONN] = PM8150b_SRC_RD_RA_VCONN,
	[SRC_TYPE_MASK] = PM8150b_DETECTED_SRC_TYPE_MASK,
};

QPTC_REG(SRC_STATUS, src_status, PM8150b_TYPEC_SRC_STATUS_REG);

static const u8 qptc_reg_vbus_status_fields[] = {
	[VBUS_VSAFE5V] = PM8150b_TYPEC_SM_VBUS_VSAFE5V,
	[VBUS_VSAFE0V] = PM8150b_TYPEC_SM_VBUS_VSAFE0V,
};

QPTC_REG(VBUS_STATUS, vbus_status, PM8150b_TYPEC_SM_STATUS_REG);

static const u8 qptc_reg_misc_status_fields[] = {
	[WATER_DETECTION_STATUS] = PM8150b_TYPEC_WATER_DETECTION_STATUS,
	[SNK_SRC_MODE] = PM8150b_SNK_SRC_MODE,
	[VBUS_DETECT] = PM8150b_TYPEC_VBUS_DETECT,
	[VBUS_ERROR_STATUS] = PM8150b_TYPEC_VBUS_ERROR_STATUS,
	[DEBOUNCE_DONE] = PM8150b_TYPEC_DEBOUNCE_DONE,
	[CC_ORIENTATION] = PM8150b_CC_ORIENTATION,
	[CC_ATTACHED] = PM8150b_CC_ATTACHED,
};

QPTC_REG(MISC_STATUS, misc_status, PM8150b_TYPEC_MISC_STATUS_REG);

static const u8 qptc_reg_mode_cfg_fields[] = {
	[TRY_MODE_MASK] = PM8150b_TYPEC_TRY_MODE_MASK,
	[EN_TRY_SNK] = PM8150b_EN_TRY_SNK,
	[EN_TRY_SRC] = PM8150b_EN_TRY_SRC,
	[POWER_ROLE_CMD_MASK] = PM8150b_TYPEC_POWER_ROLE_CMD_MASK,
	[EN_SRC_ONLY] = PM8150b_EN_SRC_ONLY,
	[EN_SNK_ONLY] = PM8150b_EN_SNK_ONLY,
	[DISABLE_CMD] = PM8150b_TYPEC_DISABLE_CMD,
};

QPTC_REG(MODE_CFG, mode_cfg, PM8150b_TYPEC_MODE_CFG_REG);

static const u8 qptc_reg_vconn_cfg_fields[] = {
	[VCONN_EN_ORIENTATION] = PM8150b_VCONN_EN_ORIENTATION,
	[VCONN_EN_VALUE] = PM8150b_VCONN_EN_VALUE,
	[VCONN_EN_SRC] = PM8150b_VCONN_EN_SRC,
};

QPTC_REG(VCONN_CFG, vconn_cfg, PM8150b_TYPEC_VCONN_CONTROL_REG);

static const u8 qptc_reg_exit_state_cfg_fields[] = {
	[BYPASS_VSAFE0V_DURING_ROLE_SWAP] = PM8150b_BYPASS_VSAFE0V_DURING_ROLE_SWAP,
	[SEL_SRC_UPPER_REF] = PM8150b_SEL_SRC_UPPER_REF,
	[USE_TPD_FOR_EXITING_ATTACHSRC] = PM8150b_USE_TPD_FOR_EXITING_ATTACHSRC,
	[EXIT_SNK_BASED_ON_CC] = PM8150b_EXIT_SNK_BASED_ON_CC,
};

QPTC_REG(EXIT_STATE_CFG, exit_state_cfg, PM8150b_TYPEC_EXIT_STATE_CFG_REG);

static const u8 qptc_reg_currsrc_cfg_fields[] = {
	[SRC_RP_SEL_MASK] = PM8150b_TYPEC_SRC_RP_SEL_MASK,
	[SRC_RP_SEL_330UA] = PM8150b_TYPEC_SRC_RP_SEL_330UA,
	[SRC_RP_SEL_180UA] = PM8150b_TYPEC_SRC_RP_SEL_180UA,
	[SRC_RP_SEL_80UA] = PM8150b_TYPEC_SRC_RP_SEL_80UA,
};

QPTC_REG(CURRSRC_CFG, currsrc_cfg, PM8150b_TYPEC_CURRSRC_CFG_REG);

static const u8 qptc_reg_intr_1_cfg_fields[] = {
	[LEGACY_CABLE_INT_EN] = PM8150b_TYPEC_LEGACY_CABLE_INT_EN,
	[NONCOMPLIANT_LEGACY_CABLE_INT_EN] = PM8150b_TYPEC_NONCOMPLIANT_LEGACY_CABLE_INT_EN,
	[TRYSOURCE_DETECT_INT_EN] = PM8150b_TYPEC_TRYSOURCE_DETECT_INT_EN,
	[TRYSINK_DETECT_INT_EN] = PM8150b_TYPEC_TRYSINK_DETECT_INT_EN,
	[CCOUT_DETACH_INT_EN] = PM8150b_TYPEC_CCOUT_DETACH_INT_EN,
	[CCOUT_ATTACH_INT_EN] = PM8150b_TYPEC_CCOUT_ATTACH_INT_EN,
	[VBUS_DEASSERT_INT_EN] = PM8150b_TYPEC_VBUS_DEASSERT_INT_EN,
	[VBUS_ASSERT_INT_EN] = PM8150b_TYPEC_VBUS_ASSERT_INT_EN,
};

#define INTR_1_CFG_FIELDS			  \
	(BIT(LEGACY_CABLE_INT_EN)		| \
	BIT(NONCOMPLIANT_LEGACY_CABLE_INT_EN)	| \
	BIT(TRYSOURCE_DETECT_INT_EN)		| \
	BIT(TRYSINK_DETECT_INT_EN)		| \
	BIT(CCOUT_DETACH_INT_EN)			| \
	BIT(CCOUT_ATTACH_INT_EN)			| \
	BIT(VBUS_DEASSERT_INT_EN)		| \
	BIT(VBUS_ASSERT_INT_EN))

QPTC_REG(INTR_1_CFG, intr_1_cfg, PM8150b_TYPEC_INTERRUPT_EN_CFG_1_REG);

static const u8 qptc_reg_intr_2_cfg_fields[] = {
	[STATE_MACHINE_CHANGE_INT_EN] = PM8150b_TYPEC_STATE_MACHINE_CHANGE_INT_EN,
	[VBUS_ERROR_INT_EN] = PM8150b_TYPEC_VBUS_ERROR_INT_EN,
	[DEBOUNCE_DONE_INT_EN] = PM8150b_TYPEC_DEBOUNCE_DONE_INT_EN,
};

#define INTR_2_CFG_FIELDS			  \
	(BIT(STATE_MACHINE_CHANGE_INT_EN)	| \
	BIT(VBUS_ERROR_INT_EN)			| \
	BIT(DEBOUNCE_DONE_INT_EN))

QPTC_REG(INTR_2_CFG, intr_2_cfg, PM8150b_TYPEC_INTERRUPT_EN_CFG_2_REG);

static const struct qptc_reg *pm8150b_regs[] = {
	[SNK_STATUS] = &qptc_reg_snk_status,
	[SRC_STATUS] = &qptc_reg_src_status,
	[VBUS_STATUS] = &qptc_reg_vbus_status,
	[MISC_STATUS] = &qptc_reg_misc_status,
	[MODE_CFG] = &qptc_reg_mode_cfg,
	[VCONN_CFG] = &qptc_reg_vconn_cfg,
	[EXIT_STATE_CFG] = &qptc_reg_exit_state_cfg,
	[CURRSRC_CFG] = &qptc_reg_currsrc_cfg,
	[INTR_1_CFG] = &qptc_reg_intr_1_cfg,
	[INTR_2_CFG] = &qptc_reg_intr_2_cfg,
};

const struct qptc_regs qcom_pmic_typec_pm8150b_regs = {
	.intr_1_fmask = INTR_1_CFG_FIELDS,
	.intr_2_fmask = INTR_2_CFG_FIELDS,
	.n_regs = ARRAY_SIZE(pm8150b_regs),
	.regs = pm8150b_regs,
};
